### ISSUE TITLE
Splatoon 3 amiibo original IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#104]
Octoling blue
08050200041B0402

Inkling yellow
0800010004150402

Smallfry
08060100041C0402

**Comment by AbandonedCart** [comment]
Converted this to a PR with you as co-author https://github.com/N3evin/AmiiboAPI/pull/105

**Comment by N3evin** [comment]
PR had been merged and deployed to server.
