### ISSUE TITLE
Incorrect Compatibility

### ISSUE THREAD

**Issue by MMMMMMMMTTYYY** [N3evin/AmiiboAPI#107]
i found a little mistake  
on the Zelda & Loftwing amiibo page it claims it works for smash 3ds and Wii U, it doesn't
![F075EDE4-26CE-44DD-9BBE-8B72CABA40D0](https://user-images.githubusercontent.com/102836074/202195930-5b0e1475-d2c5-4d3a-9be5-3a3d51c41346.jpeg)

**Comment by N3evin** [comment]
Try putting the issue into as the game list is generated from that repo

https://github.com/MrKev312/AmiiboGameListGenerator
