### ISSUE TITLE
Kazuya and Sephiroth Original IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#110]
Sephiroth
3601000004210002

Kazuya
33C0000004200002
![IMG_20230113_123758](https://user-images.githubusercontent.com/115247704/212311981-29f55b10-cc73-431a-a1a8-378f938a897f.jpg)

**Comment by cheatfreak47** [comment]
Can confirm these IDs are correct, thanks!

**Comment by N3evin** [comment]
Will add it in once I'm home :)

**Comment by N3evin** [comment]
Added: https://github.com/N3evin/AmiiboAPI/commit/9e75a17267b2e6e298619008021b1d808c231067
