### ISSUE TITLE
TotK Zelda and Gerudo King Amiibo

### ISSUE THREAD

**Issue by Nova77x** [N3evin/AmiiboAPI#131]
0100000004190902 Zelda
01000000041A0902 Gerudo King

**Comment by Brickleberry19** [comment]
This 2 IDs are Not from real amiibo they are ripped Out of the game. AmiiboAPI only Accept IDs from real and official amiibo

**Comment by cheatfreak47** [comment]
Yeah, we don't add IDs to the database until the amiibo are released unless they are verifiably from a source with an early physical amiibo dump.

These IDs are almost certainly correct but it's just part of the way we vet data.
