### ISSUE TITLE
Less strict queries.

### ISSUE THREAD

**Issue by Slluxx** [N3evin/AmiiboAPI#132]
This url works: https://www.amiiboapi.com/api/amiibo/?name=Link+-+Ocarina+of+Time
This url does not: https://www.amiiboapi.com/api/amiibo/?name=Ocarina+of+Time (404)

**All** queries should return partial results, not just 100% matches. 

Also, if nothing can be found, the current response is 404
```json
{
  "code": 404,
  "error": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
```

However the url is correct, so it shouldnt respond with 404 but an empty amiibo array.

**Comment by N3evin** [comment]
Thanks for finding that bug. Wonder why no body complains about it. But I am doing a PR to the 404 issues right now. For the partial text search, I had something I did previously, I only allow character name and amiibo name for the partial search. I will push it up. 

#133

**Comment by N3evin** [comment]
I had do the same for gameseries name and amiibo series name, to allow partial lookup

**Comment by AbandonedCart** [comment]
> Thanks for finding that bug. Wonder why no body complains about it.

Given the presentation of being an API, quirks like that, even though we know they exist, can be easily overlooked as "my problem, not yours."
