### ISSUE TITLE
Filter not working when using id instead of head/tail

### ISSUE THREAD

**Issue by thattridentdude** [N3evin/AmiiboAPI#134]
When querying with head or tail + `showusage` or `showgames` filter the response is as expected and will return usage information and game information respectively. 

E.g. `api/amiibo/?tail=023d0002&showusage` and `api/amiibo/?head=19960000&showusage` will return the following:

```
{
	"amiibo": [
		{
			"amiiboSeries": "Super Smash Bros.",
			"character": "Mewtwo",
			"gameSeries": "Pokemon",
			"games3DS": [
				{
					"amiiboUsage": [
						{
							"Usage": "Give Kirby a Copy ability based on the character's abilities and a health item",
							"write": false
						}
					],
					"gameID": [
						"0004000000189600",
						"0004000000183600",
						"0004000000189800"
					],
					"gameName": "Kirby: Planet Robobot"
				},
				{
					"amiiboUsage": [
						{
							"Usage": "Battle and train up a computer-controlled Figure Player of the character",
							"write": true
						}
					],
					"gameID": [
						"00040000000EE000",
						"00040000000EDF00"
					],
					"gameName": "Super Smash Bros. for Nintendo 3DS"
				}
			],
			"gamesSwitch": [
				{
					"amiiboUsage": [
						{
							"Usage": "Battle and train up a computer-controlled Figure Player of the character",
							"write": true
						}
					],
					"gameID": [
						"01006A800016E000"
					],
					"gameName": "Super Smash Bros. Ultimate"
				}
			],
			"gamesWiiU": [
				{
					"amiiboUsage": [
						{
							"Usage": "Unlock a character-based Mystery Mushroom costume",
							"write": false
						}
					],
					"gameID": [
						"000500001018DD00",
						"000500001018DC00",
						"000500001018DB00"
					],
					"gameName": "Super Mario Maker"
				},
				{
					"amiiboUsage": [
						{
							"Usage": "Battle and train up a computer-controlled Figure Player of the character",
							"write": true
						}
					],
					"gameID": [
						"0005000010145000",
						"0005000010144F00",
						"0005000010110E00"
					],
					"gameName": "Super Smash Bros. for Wii U"
				}
			],
			"head": "19960000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_19960000-023d0002.png",
			"name": "Mewtwo",
			"release": {
				"au": "2015-10-24",
				"eu": "2015-10-23",
				"jp": "2015-10-29",
				"na": "2015-11-13"
			},
			"tail": "023d0002",
			"type": "Figure"
		}
	]
}
```

`api/amiibo/?id=19960000023d0002&showusage` however will only return basic amiibo information:

```
{
	"amiibo": {
		"amiiboSeries": "Super Smash Bros.",
		"character": "Mewtwo",
		"gameSeries": "Pokemon",
		"head": "19960000",
		"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_19960000-023d0002.png",
		"name": "Mewtwo",
		"release": {
			"au": "2015-10-24",
			"eu": "2015-10-23",
			"jp": "2015-10-29",
			"na": "2015-11-13"
		},
		"tail": "023d0002",
		"type": "Figure"
	}
}
```

The same applies for the `showgames` filter.

As an aside, I believe heads are not unique so can't be used as identifiers. Do we know if all tails are unique and could serve that purpose in lieu of using the full id?

**Comment by N3evin** [comment]
I would recommend to actually stack head and tail together + showusage to be more precise. Possible to test it out?

**Comment by thattridentdude** [comment]
> I would recommend to actually stack head and tail together + showusage to be more precise. Possible to test it out?

Good idea, hadn't thought of testing head and tail together! 
`amiibo/?tail=023d0002&head=19960000&showusage` works properly and yields the expected result. 

So basically everything except `id=value&showusage` and `id=value&showgames` works. `head`, `tail` and a combination of both in any order works properly. 

> Edit: The reason for splitting head and tail is just the bytes and it make it easier for us to read the info such as series, character and type. So to answer to your questions, just either head or tail can't be used as an identifier since an amiibo id is both head + tail.

Thanks for the clarification. 
I suspected as much, but since the API favors responding with head and tail I started to wonder if I was making it more complicated on myself by sticking to the full id as identifier.

**Comment by N3evin** [comment]
> 

You are right, since it allows head and tail, id will not be needed for showusage and showgames. You can easily split up the values anyway :)
