### ISSUE TITLE
Pyra and Mythra IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#135]
Pyra

ID: 22410000041E0002

 
Mythra

ID: 22420000041F0002

**Comment by cheatfreak47** [comment]
@N3evin can confirm these are valid

**Comment by N3evin** [comment]
> Pyra
> 
> ID: 22410000041E0002
> 
> Mythra
> 
> ID: 22420000041F0002

Thanks for the confirmation. Will be deploying it :) PR had been created.

**Comment by N3evin** [comment]
added :)
