### ISSUE TITLE
Jikkyou Powerful Pro Baseball, 3 Amiibo incorrect/switched around

### ISSUE THREAD

**Issue by ToddlerPichu** [N3evin/AmiiboAPI#139]
Scanning my official `Jikkyou Powerful Pro Baseball` Amiibo cards with Tagmo:
`Yabe` incorrectly shows up as `Daijobu`
`Daijobu` incorrectly shows up as `Ganda`
and `Ganda` incorrectly shows up as `Yabe`

**Comment by cheatfreak47** [comment]
How strange, I suppose it's possible the data for these ones we have is wrong- as I've only ever gotten these dumped once a very long time ago, maybe the original dumps we used to fill in this data were mislabeled.

Can anyone else with these cards confirm this issue?

**Comment by Brickleberry19** [comment]
Yabe is Ganda
Daijobu is Yabe
Haykawa is Hayakawa
Pawapuro is Pawapuro
Ikari is Ikari
Ganda is Daijobu

**Comment by ToddlerPichu** [comment]
> Yabe is Ganda
> Daijobu is Yabe
> Haykawa is Hayakawa
> Pawapuro is Pawapuro
> Ikari is Ikari
> Ganda is Daijobu

Would you mind double checking that, or phrasing it another way, because the way I am reading it seems backwards from what I got:
`Yabe (003-AI-G0J) card` shows as `Daijobu (006-AI-G0J) in database`
`Daijobu (006-AI-G0J) card` incorrectly shows up as `Ganda (005-AI-G0J) in database`
and `Ganda (005-AI-G0J) card` incorrectly shows up as `Yabe (003-AI-G0J) in database`

**Comment by Brickleberry19** [comment]
> > Yabe is Ganda
> > Daijobu is Yabe
> > Haykawa is Hayakawa
> > Pawapuro is Pawapuro
> > Ikari is Ikari
> > Ganda is Daijobu
> 
> Would you mind double checking that, or phrasing it another way, because the way I am reading it seems backwards from what I got:
> `Yabe (003-AI-G0J) card` shows as `Daijobu (006-AI-G0J) in database`
> `Daijobu (006-AI-G0J) card` incorrectly shows up as `Ganda (005-AI-G0J) in database`
> and `Ganda (005-AI-G0J) card` incorrectly shows up as `Yabe (003-AI-G0J) in database`

Amiibo File name > the correctly Card name

**Comment by Brickleberry19** [comment]
"0x3800000103931702": {

      "name": "Pawapuro",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

    "0x3801000103941702": {

      "name": "Ikari",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

    "0x3802000103951702": {

      "name": "Yabe",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

    "0x3803000103961702": {

      "name": "Hayakawa",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

    "0x3804000103971702": {

      "name": "Ganda",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

    "0x3805000103981702": {

      "name": "Daijobu",

      "release": {

        "au": null,

        "eu": null,

        "jp": "2019-06-27",

        "na": null

      }

    },

**Comment by Brickleberry19** [comment]
a friend tried the files in the game and these results came about that I wrote above, I can't explain why yours and mine are so different

**Comment by ToddlerPichu** [comment]
>Amiibo File name > the correctly Card name
>> a friend tried the files in the game and these results came about that I wrote above, I can't explain why yours and mine are so different

I think ours do match up... i had listed card scanned first and then the result gotten, if that was the in correct way to order things I apologize. Your list seems to be the reverse of mine, file name in the API first and then what the correct card is supposed to be, yes?
Either way looking at your info, it does match up with mine
`Daijobu 0x3805000103981702`, `Ganda 0x3804000103971702`, `Yube 0x3802000103951702`

Compared to the incorrect [API](https://amiiboapi.com/api/amiibo/):
>{
      "amiiboSeries": "Power Pros",
      "character": "Daijobu",
      "gameSeries": "Power Pros",
      "head": "38020001",
      "image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_38020001-03951702.png",
      "name": "Daijobu",
      "release": {
        "au": null,
        "eu": null,
        "jp": "2019-06-27",
        "na": null
      },
      "tail": "03951702",
      "type": "Card"
    },
> {
      "amiiboSeries": "Power Pros",
      "character": "Ganda",
      "gameSeries": "Power Pros",
      "head": "38050001",
      "image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_38050001-03981702.png",
      "name": "Ganda",
      "release": {
        "au": null,
        "eu": null,
        "jp": "2019-06-27",
        "na": null
      },
      "tail": "03981702",
      "type": "Card"
    },
> {
      "amiiboSeries": "Power Pros",
      "character": "Yabe",
      "gameSeries": "Power Pros",
      "head": "38040001",
      "image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_38040001-03971702.png",
      "name": "Yabe",
      "release": {
        "au": null,
        "eu": null,
        "jp": "2019-06-27",
        "na": null
      },
      "tail": "03971702",
      "type": "Card"
    },

**Comment by Brickleberry19** [comment]
I think the best way to Sort it Out, is that you write Cheatfreak on discord

**Comment by ToddlerPichu** [comment]
Yes, I have sent the friend request already.  Please excuse any poor formatting my comments and responses may have had... I appreciate you providing results from your side and past the confusion or our 2 different orders, I do believe we have the same result.

**Comment by cheatfreak47** [comment]
Okay so it seems like I got a second confirmation of the error here, so I've updated the spreadsheet and informed the amiibo.life guy of the change, if someone could submit a pull request to fix the database and image names for the API, I can have that pulled pretty quickly, either that or nevin will fix it when he has time.

**Comment by Brickleberry19** [comment]
Here are the Images With the correct icon_
![icon_38040001-03971702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/7a6b43a6-96f8-49ed-bcd6-dd3922b5611e)

![icon_38050001-03981702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/5fb48321-0268-47dc-ae6c-1659791d8e34)

![icon_38020001-03951702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/95638129-f330-471a-87e7-e13af1cac1b9)

![icon_38000001-03931702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/a429e734-cdd7-4c49-86ab-702ccd578a89)

![icon_38010001-03941702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/b36a9fe5-0fcc-41f6-8aff-25646a0ab6ee)

![icon_38030001-03961702.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/27a8412a-e7df-4474-9a44-fd4f142c6da5)

**Comment by AbandonedCart** [comment]
@Brickleberry19 The file names get stripped when uploading them as images.

**Comment by Brickleberry19** [comment]
@AbandonedCart thanks for the hint

**Comment by cheatfreak47** [comment]
thanks for the quick fix, nevin 👍

**Comment by N3evin** [comment]
hey everyone!! Thank you for updating us on the issue :) I had deployed the fix. Can somoene test it?

**Comment by Brickleberry19** [comment]
@N3evin it works
