### ISSUE TITLE
Official Deep Cut amiibo IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#150]
![3. Shiver.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/ff47e67c-6bc3-4247-939f-a3d2e5ae29cd)

![5. Big Man.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/dd7dbdea-e3f8-4a8b-8cc7-f11085653efb)

![4. Frye.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/0da6e52b-7e9d-43d8-ad98-c635da23f1c5)

I'll send the IDs etc. in about 3-4 hours

**Comment by Brickleberry19** [comment]
0x0807000004330402": {
      "name": "Shiver",
      "release": {
        "au": "2023-11-17",
        "eu": "2023-11-17",
        "jp": "2023-11-17",
        "na": "2023-11-17"
      }
    },

0x0808000004340402": {
      "name": "Frye",
      "release": {
        "au": "2023-11-17",
        "eu": "2023-11-17",
        "jp": "2023-11-17",
        "na": "2023-11-17"
      }
    },

0x0809000004350402": {
      "name": "Big Man",
      "release": {
        "au": "2023-11-17",
        "eu": "2023-11-17",
        "jp": "2023-11-17",
        "na": "2023-11-17"
      }
    },

Shiver
icon_08070000-04330402.png
Frye
icon_08080000-04340402.png
Big Man
icon_08090000-04350402.png

**Comment by N3evin** [comment]
Done :)
https://github.com/N3evin/AmiiboAPI/pull/151
