### ISSUE TITLE
A few names are incorrect (animal crossing)

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#154]
rosco is missing an e at the end, the correct name is roscoe
The ID is 0x03a8000100910502

Label is missing a le at the end, With the ID 0x0189000100ab0502

the correct name is Label with the ID 0x0189010103b10502

**Comment by N3evin** [comment]
Done :)
https://github.com/N3evin/AmiiboAPI/pull/155
