### ISSUE TITLE
Official Sora amiibo ID

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#162]
I should have my Sora amiibo tomorrow, so I open this here in advance, as soon as I get mine I'll edit the text.

0x3f000000042e0002": {
      "name": "Sora",
      "release": {
        "au": "2024-02-16",
        "eu": "2024-02-16",
        "jp": "2024-02-16",
        "na": "2024-02-16"
      }
    },

icon_3f000000-042e0002.png

- https://amiibo.life/amiibo/super-smash-bros/sora

![Sora.png](https://github.com/N3evin/AmiiboAPI/assets/115247704/76b006e8-3a4c-4cb6-b9be-85c20fc94096)

**Comment by AbandonedCart** [comment]
![304868944-76b006e8-3a4c-4cb6-b9be-85c20fc94096](https://github.com/N3evin/AmiiboAPI/assets/1173913/1a2d71b8-9fcc-4cfc-a566-4ab0f53a590a)

Went ahead and removed the padding to avoid the extra commit.

**Comment by Brickleberry19** [comment]
> Went ahead and removed the padding to avoid the extra commit.

Thanks and What are a padding so i can remove it the next time by myself ?

**Comment by AbandonedCart** [comment]
It's the blank space around the image. It can be a hassle to manually try to crop it, but Photoshop lets you select the subject and then crop to it.

**Comment by Brickleberry19** [comment]
> It's the blank space around the image. It can be a hassle to manually try to crop it, but Photoshop lets you select the subject and then crop to it.

Ah okay thank you.
Is There a Tutorial or Something? The only Editor i use is pixlr Express

**Comment by AbandonedCart** [comment]
Assuming the magic wand works the same as Photoshop, you would use that to select the blank area, then invert selection and crop. https://blog.pixlr.com/cutting-things-out-the-easy-way-using-the-magic-wand/ explains most of that,

**Comment by Brickleberry19** [comment]
ID is added
