### ISSUE TITLE
[Documentation] Get Amiibos by AmiiboSeries

### ISSUE THREAD

**Issue by AndreasWebdev** [N3evin/AmiiboAPI#18]
Hello, I've tried the following api request from the documentation:

`http://www.amiiboapi.com/api/amiibo/?series=BoxBoy!`

The expected result would be to get all amiibos from the amiibo series "BoxBoy!". However the return includes all possible amiibos from the database.

I also tried out following api request, similar to the one in the documentation:

`http://www.amiiboapi.com/api/amiibo/?series=0x334`

Which should return all amiibos from the "Bayonetta" amiibo series, but again displays all amiibos.

Upon further inspection, it seems as you have to use the parameter amiiboSeries instead of series, so it seems like a fault in the documentation.

Pull Request: #20

**Comment by N3evin** [comment]
I will update you the documents tonight. Thank you

**Comment by AndreasWebdev** [comment]
https://github.com/N3evin/AmiiboAPI/pull/20
