### ISSUE TITLE
Splatoon 3 Alterna & Side Order IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#181]
I preordered both sets, so I open this here in advance, as soon as I get mine I'll edit the text.

0x0801000004360402": {
      "name": "Callie (Alterna)",
      "release": {
        "au": "2024-09-05",
        "eu": "2024-09-05",
        "jp": "2024-09-05",
        "na": "2024-09-05"
      }
    },

icon_08010000-04360402.png

https://amiibo.life/amiibo/splatoon/callie-alterna

0x0802000004370402": {
      "name": "Marie (Alterna)",
      "release": {
        "au": "2024-09-05",
        "eu": "2024-09-05",
        "jp": "2024-09-05",
        "na": "2024-09-05"
      }
    },

icon_08020000-04370402.png

https://amiibo.life/amiibo/splatoon/marie-alterna

0x0803000004380402": {
      "name": "Pearl (Side Order)",
      "release": {
        "au": "2024-09-05",
        "eu": "2024-09-05",
        "jp": "2024-09-05",
        "na": "2024-09-05"
      }
    },

icon_08030000-04380402.png

https://amiibo.life/amiibo/splatoon/pearl-side-order

0x0804000004390402": {
      "name": "Marina (Side Order)",
      "release": {
        "au": "2024-09-05",
        "eu": "2024-09-05",
        "jp": "2024-09-05",
        "na": "2024-09-05"
      }
    },

icon_08040000-04390402.png

https://amiibo.life/amiibo/splatoon/marina-side-order

**Comment by TheDrawingCoder-Gamer** [comment]
datamined ids with precise model number:
callie (alterna) is 0x0801000004360402
pearl (side order) is 0x0803000004380402
marie (alterna) is 0x0802000004370402
marina (side order) is 0x0804000004390402

**Comment by AbandonedCart** [comment]
Yeah, I don't have the game-info, so I didn't submit a PR.

https://github.com/8bitDream/AmiiboAPI/commit/6d0fd8e22d3eef65a796115f4e8b7246aea0839d

If anyone wants to cherry-pick that and add the game-info feel free to submit it.

**Comment by Brickleberry19** [comment]
> Yeah, I don't have the game-info, so I didn't submit a PR.
> 
> https://github.com/8bitDream/AmiiboAPI/commit/6d0fd8e22d3eef65a796115f4e8b7246aea0839d
> 
> If anyone wants to cherry-pick that and add the game-info feel free to submit it.

So I don't need to change the text tomorrow?

**Comment by AbandonedCart** [comment]
May want to verify it just to be sure.

**Comment by AbandonedCart** [comment]
> So I don't need to change the text tomorrow?

It would be good to verify them just to be safe. Thanks.

**Comment by N3evin** [comment]
https://github.com/N3evin/AmiiboAPI/pull/183

**Comment by N3evin** [comment]
Gameinfo generator should now be fixed. That should also resolved older data that had not been populdated.

https://github.com/N3evin/AmiiboAPI/pull/187

**Comment by Brickleberry19** [comment]
I have now edited my first comment

**Comment by AbandonedCart** [comment]
> I have now edited my first comment

Looks like they all line up. Thanks for confirming

**Comment by Brickleberry19** [comment]
> > I have now edited my first comment
> 
> Looks like they all line up. Thanks for confirming

but apparently something is not right because in TagMo and Other Programms that use this API displays only callie with name and picture, the others have neither

**Comment by N3evin** [comment]
> > > I have now edited my first comment
> > 
> > Looks like they all line up. Thanks for confirming
> 
> but apparently something is not right because in TagMo and Other Programms that use this API displays only callie with name and picture, the others have neither

I just checked Marie data, it's ok even from api point of view. The image url is also working.

**Comment by AbandonedCart** [comment]
It may be that there was no game info when I updated TagMo, but it’s designed to handle that.

**Comment by N3evin** [comment]
> It may be that there was no game info when I updated TagMo, but it’s designed to handle that.

That I'm not too sure. But gameinfo should be populated.

https://www.amiiboapi.com/api/amiibo/?name=marie&showusage

**Comment by AbandonedCart** [comment]
Not what I meant. I haven’t pulled the game info update into TagMo yet. It only had the main database changes.

**Comment by N3evin** [comment]
Oh ok. My bad. If that's the case, will be better to check tagmo. I'm not too sure about it.

**Comment by AbandonedCart** [comment]
I’m the developer of TagMo, but we can move the conversation there.

**Comment by N3evin** [comment]
That will be great 👍

**Comment by N3evin** [comment]
Data provided in database is not correct. Will have to reverify with the data in the first comment.

Need more verification.

**Comment by AbandonedCart** [comment]
Both the mined copy and the official copy match, so I am not sure how I ended up with typos.

**Comment by Brickleberry19** [comment]
> Both the mined copy and the official copy match, so I am not sure how I ended up with typos.

I checked it and the ones from me and the ones from TheDrawingCoder-Gamer are 1:1 the same

**Comment by TheDrawingCoder-Gamer** [comment]
yeah they are the same. kind of surprised i got it right in the first place though as I only really referenced the model number and used the wiki to pull other pieces in

**Comment by AbandonedCart** [comment]
> I checked it and the ones from me and the ones from TheDrawingCoder-Gamer are 1:1 the same

Don't worry, I had the computer verify this time.

**Comment by N3evin** [comment]
Completed with new id.

**Comment by AbandonedCart** [comment]
Thanks and sorry about that. Hopefully the new id export feature in TagMo will reduce human error.
