### ISSUE TITLE
Serving HTTPS

### ISSUE THREAD

**Issue by AndreasWebdev** [N3evin/AmiiboAPI#19]
Please consider serving the api over https, as one could not use the api through a secure connection with the JS Fetch API. This also means that no GitHub Pages could use the api as they require HTTPS.

`Inline Babel script:29 Mixed Content: The page at 'https://andreaswebdev.github.io/amiibo.app/' was loaded over HTTPS, but requested an insecure resource 'http://www.amiiboapi.com/api/amiibo/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by N3evin** [comment]
I wish I could. But due to me being poor. I can't really afford an ssl certificate

**Comment by justindra** [comment]
Heroku should support it, happy to help put it on if you need a hand @N3evin

**Comment by N3evin** [comment]
That will be awesome, but the one I read that I had to pay for extra workers to get https to run.

**Comment by justindra** [comment]
Ah ok. That might possibly be the issue then. I'll have a quick look, but I thought you should be able to do it in the same worker with LetsEncrypt

**Comment by jose0ten** [comment]
Hi. I'm currently learning GraphQL and I'm using your RESTful api to fetch the amiibo data. Just wanted you to know.

That being said, I'm currently deploying it on Heroku as well and it's providing me HTTPS. I'm using Rails for the api.

**Comment by N3evin** [comment]
> Hi. I'm currently learning GraphQL and I'm using your RESTful api to fetch the amiibo data. Just wanted you to know.
> 
> That being said, I'm currently deploying it on Heroku as well and it's providing me HTTPS. I'm using Rails for the api.

How were you able to get HTTPS? Did you pay for hobby tier?

**Comment by jose0ten** [comment]
> > Hi. I'm currently learning GraphQL and I'm using your RESTful api to fetch the amiibo data. Just wanted you to know.
> > That being said, I'm currently deploying it on Heroku as well and it's providing me HTTPS. I'm using Rails for the api.
> 
> How were you able to get HTTPS? Did you pay for hobby tier?

Hobby Tier is showing up for me as the free option so that's what I'm using right now

**Comment by alexarroyoduque** [comment]
Hi. I'm creating an app and I'm hosting it in firebase. But I would need https to work correctly. I have read the previous conversation and wanted to know if something can be done about it.

**Comment by N3evin** [comment]
For now, due to the lack of funding, I could not pay for Heroku hobby tier. However, if you really need an https, you can always host it by yourself individually, since the application is open source. I am sorry for the inconvenient. :(

**Comment by AndreasWebdev** [comment]
Is there a way to fund this project? I'd like to use this API, however I don't think I would be able to actively expand it once new Amiibos get released.

**Comment by alexarroyoduque** [comment]
Ok, I had to try.
Thank you very much for your work @ N3evin.

**Comment by cheatfreak47** [comment]
If you'd like to contribute to keeping AmiiboAPI maintained and potentially setting up HTTPS properly at some point, there's a donation link on the frontpage of the website.

Hobbyist tier is 7$ a month, so we'd need at least $82+ a year to maintain it.  At the moment we pretty much nothing which is why HTTPS is probably out of the question for now, like N3evin said you can always self-host and pay for it yourself, and just clone us when we update the source, but there we go.

**Comment by N3evin** [comment]
Ok! good news! I manage to run it off my web host with SSL. So that should now redirect all http to https :) Thou I have no idea how performance will be affected. But let's give it a try.

**Comment by Bombastisch** [comment]
TagMo pulls the whole file from http://www.amiiboapi.com/api/amiibo/
This doesn't work anymore. The update feature in the app does fail. Sadly @North101 nor @HiddenRambler seem to develop the app anymore, so there is no chance of any future update.

Shouldn't the redirect do the trick automatically?

**Comment by AndreasWebdev** [comment]
@Bombastisch trying to access the http api automatically directed me to https

**Comment by AndreasWebdev** [comment]
Also, works flawlessly in my prototype @N3evin I'll make sure to donate some amount for your work!

**Comment by N3evin** [comment]
> TagMo pulls the whole file from http://www.amiiboapi.com/api/amiibo/
> This doesn't work anymore. The update feature in the app does fail. Sadly @North101 nor @HiddenRambler seem to develop the app anymore, so there is no chance of any future update.
> 
> Shouldn't the redirect do the trick automatically?

The redirect does not work on request level. So the app must handle it. Hope some third-party could pick it up.



> Also, works flawlessly in my prototype @N3evin I'll make sure to donate some amount for your work!

That's awesome, just run it via https, that should do the trick.

**Comment by N3evin** [comment]
I shall close this issue now.
