### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by AleksaaDj** [N3evin/AmiiboAPI#193]
Hi, I think the server is down, I cannot load anything, can you please check it. Thank you very much

**Comment by AleksaaDj** [comment]
Hi, thank you for the fast response, now it is working but it was not
working for 2,3 hours this morning, both the site and api

**Comment by cheatfreak47** [comment]
Hmm, well it probably was AWS fault if that was the case, I checked it at the moment I got the email and it was fine

**Comment by AleksaaDj** [comment]
Unfortunately both the site and api are down again

**Comment by N3evin** [comment]
I did not receive any notification that the site is down. It seems to still be running.

**Comment by AbandonedCart** [comment]
> Unfortunately both the site and api are down again

Are you sure it isn't a DNS issue on your end?

![AmiiboAPI - A RESTful API for Amiibo — Mozilla Firefox 11_30_2024 6_41_39 PM](https://github.com/user-attachments/assets/01d4a9cf-c614-40e8-ae3a-311be2321815)
