### ISSUE TITLE
Donkey & diddy Kong Power Up Bands IDs

### ISSUE THREAD

**Issue by Brickleberry19** [N3evin/AmiiboAPI#194]
I ordered these two bands on eBay and they should arrive in 2 weeks, so I'm opening this in advance and will change it as soon as they arrive.

0x000800030431FF02": {
"name": "Donkey Kong - Power Up Band",
"release": {
"au": "na",
"eu": "na",
"jp": "2024-12-11",
"na": "na"
}
},

icon_00080003-0431ff02.png

https://amiibo.life/amiibo/super-nintendo-world/donkey-kong-power-up-band

0x000900030432FF02": {
"name": "Diddy Kong - Power Up Band",
"release": {
"au": "na",
"eu": "na",
"jp": "2024-12-11",
"na": "na"
}
},

icon_00090003-0432ff02.png

https://amiibo.life/amiibo/super-nintendo-world/diddy-kong-power-up-band

**Comment by AbandonedCart** [comment]
https://amiibo.life/assets/figures/amiibo/super-nintendo-world/donkey-kong-power-up-band-76286ed193881fd5b7b36c6f590ee4b709881e0a2db8e17b1d5f922caf6d2e16.png

https://amiibo.life/assets/figures/amiibo/super-nintendo-world/diddy-kong-power-up-band-8867c1db77255dd35183b4a77eb986fd7940326436f5cbab3d6da4ecc8f3c4d1.png

**Comment by Brickleberry19** [comment]
Amiibo IDs added

**Comment by N3evin** [comment]
Deployed
