### ISSUE TITLE
Octoling images and character detail missing

### ISSUE THREAD

**Issue by tannyque** [N3evin/AmiiboAPI#23]
"Octoling Girl", "Octling Boy" (should be corrected to "Octoling Boy), and "Octopus" character property now reads null and have no images

**Comment by N3evin** [comment]
Fixed: https://github.com/N3evin/AmiiboAPI/commit/1bdc967f955148d0c8d735b6f87f62dd4045493d

**Comment by tannyque** [comment]
Thanks! Really like the API btw, keep up the great work!
