### ISSUE TITLE
My name is on everything!

### ISSUE THREAD

**Issue by phalt** [N3evin/AmiiboAPI#26]
Hey, I love your project, and I love that you were inspired by PokéAPI to build this!

However, I don't want to take all your credit - I can see my name on a lot of the documents still (search for "Paul") - I think you should change them to your own name :)

**Comment by N3evin** [comment]
Hey, @phalt thanks for getting back. I just thought it is right to still credit you.

**Comment by phalt** [comment]
@N3evin it's totally fine - just leave a note somewhere saying you forked the templates from pokeapi - that's it. Take credit - you did a lot of work yourself here!

**Comment by N3evin** [comment]
> @N3evin it's totally fine - just leave a note somewhere saying you forked the templates from pokeapi - that's it. Take credit - you did a lot of work yourself here!

Thanks mate I will do it then :)
