### ISSUE TITLE
Typo on "What is this?"

### ISSUE THREAD

**Issue by d1nzy** [N3evin/AmiiboAPI#27]
"This is RESTful API that contains the Amiibo Database that was **createed** on the excel spreadsheet.

It will be regulary updated as new amiibo is release."

Not really a bug, just a typo.

**Comment by N3evin** [comment]
Fixed: https://github.com/N3evin/AmiiboAPI/commit/915073be6a1d44fe3e8a8549639520f1c1503f1e
