### ISSUE TITLE
all missing fire emblem tag id's

### ISSUE THREAD

**Issue by cryptolute** [N3evin/AmiiboAPI#29]
Here's the remaining (that I know of) fire emblem amiibo tag id's that are not already added. thanks!

Corrin	  21050000025A0002
Corrin P2   2105010003630002
ike 	          2101000000180002
Lucina	  2102000000290002
Marth	  21000000000B0002
Robin	  21030000002A0002
Roy	          2104000002520002

**Comment by N3evin** [comment]
They are all already added.
https://www.amiiboapi.com/api/amiibo/?gameseries=Fire%20Emblem
