### ISSUE TITLE
I can't access the "https://www.amiiboapi.com/api/amiibo/".

### ISSUE THREAD

**Issue by aniac0105** [N3evin/AmiiboAPI#30]
I can't access the "https://www.amiiboapi.com/api/amiibo/".
Please check that.
Thank you.

**Comment by N3evin** [comment]
Thank you! Seems like the webserver is down. I will check with the host.

**Comment by N3evin** [comment]
Issue fixed :)

**Comment by aniac0105** [comment]
Thank you very much.
Have a nice day.
