### ISSUE TITLE
Game usage support

### ISSUE THREAD

**Issue by MrKev312** [N3evin/AmiiboAPI#32]
Will it be possible to see the titleid's of games that the amiibo is usable in?
Like in the json add arrays for WiiU, Switch and 3DS with gameid's of the games

**Comment by N3evin** [comment]
Hi! Currently, I have no plans to implement it into the api, as it's just a simple data retrieve of amiibo's basic information.

**Comment by mrbob312** [comment]
Since Nintendo does show the games the amiibo can be used in, it should be possible to scrape the data off the site

**Comment by N3evin** [comment]
> Since Nintendo does show the games the amiibo can be used in, it should be possible to scrape the data off the site

Yeah true. Feel free to go ahead and scrap and do a pull request :) Currently I am busy, so I would really have any time to create new features.

**Comment by mrbob312** [comment]
Just noticed, Nintendo doesn't list Smash Ultimate for the new ones

**Comment by N3evin** [comment]
> Just noticed, Nintendo doesn't list Smash Ultimate for the new ones

that's a waste. Feel free to improve it in anyway.

**Comment by mrbob312** [comment]
So far got all Wii U games to parse, now the Switch and 3DS

**Comment by mrbob312** [comment]
Got Switch and 3DS working now too! I think I send way too many requests so the amiibo.life site is very slow for me at the moment so I'll need to regenerate the list later, also github doesn't seem to like uploading the program so I'll try uploading it later

**Comment by mrbob312** [comment]
[AmiiboGameList.zip](https://github.com/N3evin/AmiiboAPI/files/4386695/AmiiboGameList.zip)
Here's the zip with both the program and the generated JSON (Incomplete due to missing games on the 3DS and Switch database)

**Comment by N3evin** [comment]
Thanks! I will take it look during my free time :)

**Comment by mrbob312** [comment]
I'm gonna fix some stuff and resend it

**Comment by mrbob312** [comment]
Here's the updated version
[Amiibo.zip](https://github.com/N3evin/AmiiboAPI/files/4389052/Amiibo.zip)

**Comment by mrbob312** [comment]
How's it going with importing?

**Comment by N3evin** [comment]
> How's it going with importing?
Currently I am busy with my work. Sorry about it. I will look at it when I am available.

**Comment by oscarg798** [comment]
So I'm doing kind of the same feature on an app using this API, [AmiiboWiki](https://github.com/oscarg798/AmiiboWiki ), but what I'm doing is getting games  from [IGDB](https://www.igdb.com/discover), let me know if you want to do something from here

**Comment by N3evin** [comment]
> So I'm doing kind of the same feature on an app using this API, [AmiiboWiki](https://github.com/oscarg798/AmiiboWiki), but what I'm doing is getting games from [IGDB](https://www.igdb.com/discover), let me know if you want to do something from here

In a way, you can use IGDB and just combined with amiiboapi? If that's the case if anyone wants to do it. Then can just call both API? My idea was just to keep it as a simple amiibo details.

**Comment by MrKev312** [comment]
I started working on this on my own fork, got a few bits working so far

**Comment by MrKev312** [comment]
@N3evin, I think I'm done with [the implementation](https://github.com/MrKev312/AmiiboAPI), is it good as is? If so I'll make a pull request

**Comment by N3evin** [comment]
It's really good. But could I throw in a suggestion? Because the database is getting larger with the amiibo. Was wondering, if we could separate the game database, this make a separate game API route, which they can use. as the amiibo database was supposed to keep in simple. If we don't need another API routes for game it's also fine. But then maybe a way to join from 2 json file? For example, when need `amiibofull/amiiboname?character=zelda`, just combine the both look out from json.

games_info.json
```
{
       "0x0000000000000002": {
			"games3DS": [
				{
					"gameName": "Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey",
					"gameID": [
						"00040000001D1500",
						"00040000001D1400"
					],
					"amiiboUsage": [
						{
							"Usage": "Receive a helpful item",
							"write": false
						}
					]
				},
				......
}
```

 2nd, what happened if added a new amiibo that does not have the necessary game info? For example, we might not immediately get a new game id or amiibousage on a brand new amiibo.

**Comment by MrKev312** [comment]
Good idea! I'll try working on that. For the 2nd; if something doesn't have certain game info, it'll just be an empty array. Since some games have multiple uses and multiple IDs it's already an array:
```
{
       "0x0000000000000002": {
			"games3DS": [
				{
					"gameName": "Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey",
					"gameID": [],
					"amiiboUsage": []
				},
				......
}
```

**Comment by N3evin** [comment]
Thanks for the hardwork. Great, I guess as long as it's not breaking it that should be fine. I will try to do more test. But this information is amazing. Is it easy to scrap?

**Comment by MrKev312** [comment]
I've decided to only store the games where they have a distinct thing they do, but I could also include the games that work with any amiibo (although it would make the json even bigger), Hyrule Warriors is one of those games

**Comment by N3evin** [comment]
Hmmm, true that. But does it necessary to show the info of what they do? Won't be ok with just game id and name? The info is not really specific and I guess people could just try out in the game at the end. Pretty obvious enough imo.

**Comment by MrKev312** [comment]
I've kept it in there because maybe a program that can see which game is running could show which amiibos can be used and what they do, it can even see if that would also write to the amiibo. I think there's a homebrew for the switch which emulates amiibos and can have per game saves, with this it could see if it would need to make a new save file for the game. It could, if needed, be required to pass an `?usagedetails=true` argument to show it

**Comment by MrKev312** [comment]
The only game missing is Shovel Knight Showdown (Wii U), I haven't been able to find the ID(s) of that game anywhere

**Comment by MrKev312** [comment]
Is this what you meant? (I'll try getting the ordering to be normal)
[Amiibo.zip](https://github.com/N3evin/AmiiboAPI/files/6016133/Amiibo.zip)

**Comment by N3evin** [comment]
> Is this what you meant? (I'll try getting the ordering to be normal)
> [Amiibo.zip](https://github.com/N3evin/AmiiboAPI/files/6016133/Amiibo.zip)

yup! That's it! just rename the file to something like `games_info.json`and merge the 2 data required when retriving the amiibofull :) That is awesome.



> The only game missing is Shovel Knight Showdown (Wii U), I haven't been able to find the ID(s) of that game anywhere

interesting, I guess not every details is possible. Tmr, I will try to see if I know anyone that could get it.





> I've kept it in there because maybe a program that can see which game is running could show which amiibos can be used and what they do, it can even see if that would also write to the amiibo. I think there's a homebrew for the switch which emulates amiibos and can have per game saves, with this it could see if it would need to make a new save file for the game. It could, if needed, be required to pass an `?usagedetails=true` argument to show it

Oh that I do not know, but of that's the case. Won't game_id and game_name be sufficient? We don't need the `amiiboUsage` for the info right? The amiiboUsage.info and amiiboUsage.write will not be neccessary in our end. That will just be the switch homebrew app handle. It's not an info for our purpose.

**Comment by N3evin** [comment]
I'm just boiling down to what amiiboapi does. If how's the game handle should be handled by the homebrew or other other api.

As it's not related to amiibo.

**Comment by MrKev312** [comment]
> It's really good. But could I throw in a suggestion? Because the database is getting larger with the amiibo. Was wondering, if we could separate the game database, this make a separate game API route, which they can use, as the amiibo database was supposed to keep in simple. If we don't need another API routes for game it's also fine. But then maybe a way to join from 2 json file? For example, when need `amiibofull/amiiboname?character=zelda`, just combine the both look out from json.

After rereading this, do you mean the final database (the api/amiibo) or the database in the github repo? I kept the functionality of api/amiibo the same and put all the game stuff under api/amiibofull

**Comment by N3evin** [comment]
The GitHub database database/amiibo.json, so I was suggesting to pluck out the game stuff to database/games_info.json

**Comment by MrKev312** [comment]
So I got the 2 jsons working, since that partly changed how I handle amiibo I was trying to mix them both into the api/amiibo url and add a `?showgames` tag which only works if it's in front of all other tags. This got me to try `api/amiibo/?name=mario?tail=00340102` to see how multi-tag searches work and I got a 404 and the console revealed `params={'name': 'mario?tail=00340102'}`, looks like for this to work the whole tag/filtering system would need a rework, so for now I'll keep it in two different routes

**Comment by MrKev312** [comment]
2 jsons is now perfectly working, now has the `api/amiibo/?name=mario&showgames` and `api/amiibo/?name=mario&showusage` implemented

**Comment by N3evin** [comment]
> 2 jsons is now perfectly working, now has the `api/amiibo/?name=mario&showgames` and `api/amiibo/?name=mario&showusage` implemented

tested and it seems great! Do you mind updating the documentation page? Then go ahead and do the pull request :)

**Comment by MrKev312** [comment]
Added the documentation and used a singleton pattern to speed up the load times, I'll make a pr now!

**Comment by N3evin** [comment]
> Added the documentation and used a singleton pattern to speed up the load times, I'll make a pr now!

Oh! that's a really good idea to use a singleton pattern.
