### ISSUE TITLE
Some entries have the wrong gameSeries.

### ISSUE THREAD

**Issue by The537** [N3evin/AmiiboAPI#34]
**This entry should show "Super Mario Odyssey" as the gameSeries.**

{
			"amiiboSeries": "Super Mario Bros.",
			"character": "Bowser",
			"gameSeries": "Super Mario",
			"head": "00050000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_00050000-03730102.png",
			"name": "Bowser - Wedding",
			"release": {
				"au": "2017-10-27",
				"eu": "2017-10-27",
				"jp": "2017-10-27",
				"na": "2017-10-27"
			},
			"tail": "03730102",
			"type": "Figure"
		}
Bowser (Wedding Outfit) amiibo Figure - Super Mario Odyssey Series
Bowser is the king of the Koopas and Mario's eternal rival. He breathes fire, hurls hammers, and uses all sorts of weapons in hopes of taking out Mario. As his size suggests, he's immensely powerful. His plans aren't always the best, and sometimes he even finds himself on Mario's side. This amiibo figure shows Bowser decked out in his wedding outfit from the Super Mario Odyssey™ game.

**This entry should show "Super Mario Odyssey" as the gameSeries.**

{
			"amiiboSeries": "Super Mario Bros.",
			"character": "Peach",
			"gameSeries": "Super Mario",
			"head": "00020000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_00020000-03720102.png",
			"name": "Peach - Wedding",
			"release": {
				"au": "2017-10-27",
				"eu": "2017-10-27",
				"jp": "2017-10-27",
				"na": "2017-10-27"
			},
			"tail": "03720102",
			"type": "Figure"
		}

Peach (Wedding Outfit) amiibo Figure - Super Mario Odyssey Series
Princess Peach presides over the Mushroom Kingdom from her huge castle. Though she's often the target of Bowser's kidnapping schemes, Princess Peach is far from a simple damsel in distress. She's a natural at tennis and golf, a ferocious driver, and can more than hold her own at adventuring and battling. This amiibo figure shows Princess Peach decked out in her wedding outfit from the Super Mario Odyssey™ game.

**This entry should show "Super Mario Odyssey" as the gameSeries.**
{
			"amiiboSeries": "Super Mario Bros.",
			"character": "Mario",
			"gameSeries": "Super Mario",
			"head": "00000000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_00000000-03710102.png",
			"name": "Mario - Wedding",
			"release": {
				"au": "2017-10-27",
				"eu": "2017-10-27",
				"jp": "2017-10-27",
				"na": "2017-10-27"
			},
			"tail": "03710102",
			"type": "Figure"
		}
Mario (Wedding Outfit) amiibo Figure - Super Mario Odyssey Series
Mario never hesitates to leap into action when there's trouble in the Mushroom Kingdom. Known for saving the world (and Princess Peach) countless times from Bowser, Mario is a true super star. He's got amazing jumping skills and makes use of a wide range of transformations. Mario has also powered up into countless roles: referee, doctor, sportsman, dancer, kart racer, and many more. This amiibo figure shows Mario decked out in his wedding outfit from the Super Mario Odyssey™ game.

The following six entries show show "Breath of the wild" as the gameSeries.

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Daruk",
			"gameSeries": "The Legend of Zelda",
			"head": "01050000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01050000-03580902.png",
			"name": "Daruk",
			"release": {
				"au": "2017-11-10",
				"eu": "2017-11-10",
				"jp": "2017-11-10",
				"na": "2017-11-10"
			},
			"tail": "03580902",
			"type": "Figure"
		}

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Urbosa",
			"gameSeries": "The Legend of Zelda",
			"head": "01060000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01060000-03590902.png",
			"name": "Urbosa",
			"release": {
				"au": "2017-11-10",
				"eu": "2017-11-10",
				"jp": "2017-11-10",
				"na": "2017-11-10"
			},
			"tail": "03590902",
			"type": "Figure"
		}

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Mipha",
			"gameSeries": "The Legend of Zelda",
			"head": "01070000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01070000-035a0902.png",
			"name": "Mipha",
			"release": {
				"au": "2017-11-10",
				"eu": "2017-11-10",
				"jp": "2017-11-10",
				"na": "2017-11-10"
			},
			"tail": "035a0902",
			"type": "Figure"
		}

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Revali",
			"gameSeries": "The Legend of Zelda",
			"head": "01080000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01080000-035b0902.png",
			"name": "Revali",
			"release": {
				"au": "2017-11-10",
				"eu": "2017-11-10",
				"jp": "2017-11-10",
				"na": "2017-11-10"
			},
			"tail": "035b0902",
			"type": "Figure"
		}

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Zelda",
			"gameSeries": "The Legend of Zelda",
			"head": "01010000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01010000-03560902.png",
			"name": "Zelda",
			"release": {
				"au": "2017-03-03",
				"eu": "2017-03-03",
				"jp": "2017-03-03",
				"na": "2017-03-03"
			},
			"tail": "03560902",
			"type": "Figure"
		}

{
			"amiiboSeries": "Legend Of Zelda",
			"character": "Link",
			"gameSeries": "The Legend of Zelda",
			"head": "01000000",
			"image": "https://raw.githubusercontent.com/N3evin/AmiiboAPI/master/images/icon_01000000-03530902.png",
			"name": "Link (Archer)",
			"release": {
				"au": "2017-03-03",
				"eu": "2017-03-03",
				"jp": "2017-03-03",
				"na": "2017-03-03"
			},
			"tail": "03530902",
			"type": "Figure"
		}

**Comment by N3evin** [comment]
Hi, please do note that the gameseries are determined by the 1st 3 values of the amiibo id. So if I were to change one, all the other will be changed. For example browser - wedding `0005000003730102` and browser - ssb `0005000000140002` for more information please read https://www.3dbrew.org/wiki/Amiibo and look at our database spreadsheet https://docs.google.com/spreadsheets/d/19E7pMhKN6x583uB6bWVBeaTMyBPtEAC-Bk59Y6cfgxA

For the zelda one, we need more info if there's other data. Initially launch the guardian and bokogoblin has different ID, so we categories them differently. However, if there's more data or amiibo, maybe during BOTW2, we can then categorise them together as LOZ.
