### ISSUE TITLE
Missing Amiibo

### ISSUE THREAD

**Issue by DanTheMan827** [N3evin/AmiiboAPI#35]
The following IDs are missing:

```
01_Super Smash Bros\SSB_04_Donkey Kong.bin
0x0008000000000002

01_Super Smash Bros\SSB_10_Pikachu.bin
0x1919000000000002

01_Super Smash Bros\SSB_38_Palutena.bin
0x0742000000000002

01_Super Smash Bros\SSB_56_Ryu.bin
0x34c0000000000002

01_Super Smash Bros\SSB_72_Pichu.bin
0x19ac000003850002

07_Pokemon\PokemonRumble U\PokemonRumbleU_Croagunk (N2 incompatible).bin
0x83568f07e7408df8

07_Pokemon\PokemonRumble U\PokemonRumbleU_Mewtwo (N2 incompatible).bin
0xedc2c76ccf360781

07_Pokemon\PokemonRumble U\PokemonRumbleU_Piplup (N2 incompatible).bin
0xd5834c506bf2d0be

07_Pokemon\PokemonRumble U\PokemonRumbleU_Shaymin (N2 incompatible).bin
0xcbac1ea20ffcf29f
```

**EDIT:** After some researching, it seems the Pokemon Rumble U figures aren't actually Amiibo, but rather just NFC figures that the game was able to use... in any case, the hex above is what is located in the file at the same point as amiibo IDs

**Comment by N3evin** [comment]
Thank you, the other amiibo are unofficial too. Therefore, I would not be accepting them. The info are available in the pull request.

**Comment by DanTheMan827** [comment]
@N3evin I see what happened with Pichu, the key for it in the json is uppercase when all the others are lowercase, this seems like a bug.

**Comment by N3evin** [comment]
> @N3evin I see what happened with Pichu, the key for it in the json is uppercase when all the others are lowercase, this seems like a bug.

Thank you :) I had fixed it
https://github.com/N3evin/AmiiboAPI/commit/8d0681617779ce0c6f865433acf027be22466f6d
