### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by DanTheMan827** [N3evin/AmiiboAPI#40]
I created and ran a tool to validate all of the data in the json file and this is the output:
```
No amiibo part of game series: 0x194 - Pokemon
No amiibo part of game series: 0x198 - Pokemon
No amiibo part of game series: 0x19c - Pokemon
No amiibo part of game series: 0x1a0 - Pokemon
No amiibo part of game series: 0x1a4 - Pokemon
No amiibo part of game series: 0x1a8 - Pokemon
No amiibo part of game series: 0x1b0 - Pokemon
No amiibo part of game series: 0x1b4 - Pokemon
No amiibo part of game series: 0x1b8 - Pokemon
No amiibo part of game series: 0x1bc - Pokemon

No amiibo for character: 0x19AC - Pichu

Invalid amiibo character ID: 0x19AC - Pichu
```
I'm not entirely sure if I'm just parsing the ID incorrectly, or if these truly are correct.

To get the series ID I take the first 12 bits of the character ID (up to 0xFFF)

Mind you, I'm not sure if the first 12 bits is correct... 3dbrew.org says only the first 10 bits (up to 0x3FF) are part of the series ID and the remaining 6 are the character ID (up to 0x3F)

The Pichu ID also wasn't corrected in the character list.

**Comment by N3evin** [comment]
Try to set to lowercase for pichu.

**Comment by DanTheMan827** [comment]
Making the Pichu ID lowercase does in fact get rid of the errors for that, but the "No amiibo part of game series" are still present.

**Comment by N3evin** [comment]
> Making the Pichu ID lowercase does in fact get rid of the errors for that, but the "No amiibo part of game series" are still present.

because no amiibo was with those ids are released so far.

**Comment by DanTheMan827** [comment]
Why were they in the JSON then?

The tool validates the json by:

- Ensuring all keys are lowercase and match the length requirements
- Checks for missing images
- Checks for missing game series
- Checks for missing amiibo series
- Checks to make sure at least one amiibo is part of a game series ID
- Checks to make sure at least one amiibo is part of an amiibo series ID
- Checks to make sure that at least one amiibo is part of a character ID

**Comment by DanTheMan827** [comment]
You can find the source for the scanner here if you're interested, it's written in C# for .NET Core

https://github.com/DanTheMan827/AmiiboApiValidator

Maybe it'd be worthwhile to configure it as a GitHub Action for testing to catch any errors before they'd get merged?

**Comment by N3evin** [comment]
> Why were they in the JSON then?
> 
> The tool validates the json by:
> 
> * Ensuring all keys are lowercase and match the length requirements
> * Checks for missing images
> * Checks for missing game series
> * Checks for missing amiibo series
> * Checks to make sure at least one amiibo is part of a game series ID
> * Checks to make sure at least one amiibo is part of an amiibo series ID
> * Checks to make sure that at least one amiibo is part of a character ID

The reason for it being JSON is so that people can get the JSON directly via GitHub URL if they don't want to go through my API route. This was developed when I was studying that's why the data was decided to keep as JSON.

> You can find the source for the scanner here if you're interested, it's written in C# for .NET Core
> 
> https://github.com/DanTheMan827/AmiiboApiValidator
> 
> Maybe it'd be worthwhile to configure it as a GitHub Action for testing to catch any errors before they'd get merged?

Never heard of GitHub Action, this is totally new to me. Thank you, I would look at it when I had the time.
