### ISSUE TITLE
"Duplicate" amiibo cards

### ISSUE THREAD

**Issue by DanTheMan827** [N3evin/AmiiboAPI#42]
If you list all of the amiibo in the Animal Crossing series for example you'll see four Isabelle cards all listed as "Isabelle" (there are other characters too), maybe those should be differentiated in some way?

Perhaps add a series number field to the data, or maybe as part of the name?

**Comment by N3evin** [comment]
I had fixed it and label additional name. Not only to Isabelle but to some other duplicated amiibos.

https://github.com/N3evin/AmiiboAPI/commit/4bae126c6ee92c3ab826acf8abc43978d5b9260a

**Comment by DanTheMan827** [comment]
This is also a problem for the Animal Crossing figures as well, should they perhaps be listed under separate amiibo series?

On the animal crossing website, there are three Animal Crossing amiibo series listed:

- Animal Crossing: New Leaf - Welcome amiibo
- Animal Crossing (Cards)
- Animal Crossing (Figures)

https://animal-crossing.com/amiibo/

**Comment by N3evin** [comment]
Don't have to, figures and cards already had their own fields. I had already added addition tags to those duplicated names.

**Comment by N3evin** [comment]
> I'm just saying if someone used the database to rename bin files into folders with the series name and the character name for the filename, there'd be name conflicts with the figures and the cards that don't have any tags.
> 
> Maybe it was never intended to be used in such a fashion, but I'm just bringing it to your attention.

noted, but for now, I will just leave it as it is :)

**Comment by cheatfreak47** [comment]
just pointing out that it'd be best for anyone intending on using the database to rename amiibo bins should be including the full 16-digit ID in the filename if they really didn't want to have some duplicate names happening, although I am not against the idea of having series numbers, I think that'd be kinda annoying to add.
