### ISSUE TITLE
Documentation User Agent issues

### ISSUE THREAD

**Issue by yannbertrand** [N3evin/AmiiboAPI#43]
When trying to request AmiiboAPI's documentation in [a public-apis script to validate it's still running](https://github.com/public-apis/public-apis/runs/1278318858?check_suite_focus=true), we have a 404 error. We're using the `python-httplib2/0.18.0` User Agent.

It works but using `Mozilla` but using a valid User Agent should not be an issue.

```
curl -H "User-Agent:python-httplib2/0.18.0" https://www.amiiboapi.com
```

**Comment by N3evin** [comment]
It seems to be the host issue. I am checking it out with the host.

**Comment by N3evin** [comment]
Seems like I am unable to change it unless I change my host. For now, is it possible to be taken down from the listing? I will update it once I solved it.

**Comment by yannbertrand** [comment]
Alright, I'm doing it. What's your current host?

Love the projet! Thanks for being super active.

**Comment by N3evin** [comment]
> Alright, I'm doing it. What's your current host?
> 
> Love the project! Thanks for being super active.

I am currently on Namecheap Webhosting tier, the only way to solve is to host it by myself via a VPS. I will have to look into my budget if I were to solve this.

Your welcome :) I am glad that you love it.

**Comment by yannbertrand** [comment]
Would using GH Pages or Netlify be an option? (they're free)

**Comment by N3evin** [comment]
> Would using GH Pages or Netlify be an option? (they're free)

not possible for GH pages, since it hosts the whole backend logic too, Netlify bandwidth too low for the free tier. Is ok, I will just slowly see how it goes. It won't be anytime soon, since I have other commitment currently.

**Comment by yannbertrand** [comment]
Oh I didn't realize you're using the same server for the API itself.

I totally understand. Take care!
