### ISSUE TITLE
Better Id Lookups

### ISSUE THREAD

**Issue by AceHack** [N3evin/AmiiboAPI#51]
I've made a spreadsheet with every Amiibo lookup and I think it will be very helpful.  Please let me know if you would like any changes.

https://docs.google.com/spreadsheets/d/1nksa9_RWJUDhXKeAJ9CbOz7EuazxIj2yhnLXw9XWtII/edit?usp=sharing

**Comment by N3evin** [comment]
This is great! It should benefit to the community :) 

You can try posting it in
https://www.reddit.com/r/Amiibomb/

**Comment by AceHack** [comment]
I don't think I can post links, it got removed as soon as I posed it.

**Comment by N3evin** [comment]
Try contacting the admin. Maybe they will help you with the issue. Because people post links all the time in that Reddit.
