### ISSUE TITLE
mixed active content

### ISSUE THREAD

**Issue by sandwitcherz** [N3evin/AmiiboAPI#52]
Hi, when i deploy my Node App on my apache https website, console says : 
**Blocage du chargement du contenu mixte actif (mixed active content) « _http_://amiiboapi.com/api/type/ »**

BUT, in my app, i have configured whith _https_ ... : 

**const baseURL = "_https_://amiiboapi.com/api/";**

Is there an error from api?

thanks

**Comment by N3evin** [comment]
That's weird, I just tried on https://amiiboapi.com/, if you type in the box `type/` there is not issue. Are you using `type` or `type/`?

**Comment by sandwitcherz** [comment]
thanks ^^ i use this :

```
const baseURL = "https://www.amiiboapi.com/api/";
const config = [
  {
    name: "Type",
    url: "type",
    viewUrl: `${baseURL}amiibo/?type=`,
    menuData: []
  },
  {
    name: "Game Series",
    url: "gameseries",
    viewUrl: `${baseURL}amiibo/?gameseries=`,
    menuData: []
  },
  {
    name: "Series",
    url: "amiiboseries",
    viewUrl: `${baseURL}amiibo/?amiiboSeries=`,
    menuData: []
  },
  {
    name: "Character",
    url: "character",
    viewUrl: `${baseURL}amiibo/?character=`,
    menuData: []
  }
];
```

**Comment by N3evin** [comment]
Those look ok. Just tried it on amiiboapi.com

**Comment by sandwitcherz** [comment]
https://www.amiiboapi.com/api/ , https://amiiboapi.com/api/ give same error...

**Comment by N3evin** [comment]
that is weird, I guess I will find ways to duplicate when I am free. Are you running it on localhost or hosted somewhere?

**Comment by sandwitcherz** [comment]
on localhost, no problem, because the **mixed active content** is not enabled and i am on http .
I have deployed on a domain who are httpS whith letsencrypt certificat, and here appaear the error ^^

**Comment by sandwitcherz** [comment]
if you go here : https://www.amiiboapi.com/api/gameseries
this link redirrect to http://www.amiiboapi.com/api/gameseries/
who redirrects to https://amiiboapi.com/api/gameseries/

is it ok?

yes, take your time, thanks :))

**Comment by N3evin** [comment]
For now is it possible for you to just add a "/" to all your calls? this way it won't be redirected.

**Comment by N3evin** [comment]
I posted a Nginx configuration, could be that I am not configuring it right that it's causing some redirect. Due to work I won't be able to look into it much. Hoping to see if anyone can help take a look.

https://github.com/N3evin/AmiiboAPI/issues/53

**Comment by sandwitcherz** [comment]
ok i will try later, thanks N3evin :)
