### ISSUE TITLE
The server is down?

### ISSUE THREAD

**Issue by mplanckensteiner** [N3evin/AmiiboAPI#55]
Just wondering if there is any plan to continue maintaining the server?

**Comment by N3evin** [comment]
Sorry for the issue, did not notice that it was down. I will take a look

**Comment by oscarg798** [comment]
thanks, @N3evin really appreciated

**Comment by N3evin** [comment]
Seems to have issues with docker. It's back up. Sorry for the inconvenient.

**Comment by mplanckensteiner** [comment]
Thanks @N3evin!! Hope it can be back soon!

**Comment by mplanckensteiner** [comment]
Thanks @N3evin!
