### ISSUE TITLE
Need more info: Banjo, Terry and Byleth

### ISSUE THREAD

**Issue by N3evin** [N3evin/AmiiboAPI#61]
Throwing this out there. As we notice there are 2 sets of the new SSB game series ID going around, one with `003a` and another with `023d` that both had different amiibo `model ID` as stated below.

```
3b40000003a30002 - Banjo
3c80000003a40002 - Terry
210b000003a50002 - Byleth
```

```
3b400000023d0002 - Banjo
3c800000023d0002 - Terry
210b0000023d0002 - Byleth
```

For example, Megaman and Megaman (gold) had different `model ID`, but they are both 2 different amiibo. Thus this seems like the 1st case for the same version amiibos.

As of now, we are hoping for more info and legit to proof to know if there is really 2 ID going around in the market, I had added the one `03a` for now into the API.

**Comment by cheatfreak47** [comment]
Will look into this.

**Comment by N3evin** [comment]
Most bin we found are `03a`. Therefore, `23d` should be tempted files.
