### ISSUE TITLE
What's the approach to upcoming Amiibo releases?

### ISSUE THREAD

**Issue by mr-rock** [N3evin/AmiiboAPI#74]
Hi guys! I was thinking of adding to the database the _Monster Hunter Stories 2_ amiibos that will be released in July but first, I'd like to ask you guys if you guys are OK to this. If so, what approach would you recommend? 

As for the time being, as the `head` and the `tail` information of those amiibos is still unknown. I'd use some dummy head and tail information in combination with the **Monster Hunter Stories** game series and the **Figure** type to generate a temporary identifier, populate the release dates in JP and the US and to provide empty games information. And, of course, update the head/tails and games informations as soon as they are available.

Let me know what do you guys think about this, ok? ;)

**Comment by N3evin** [comment]
Hi, thank you but we do not accept dummy/spoof code. And only wait till release and got real data.

**Comment by mr-rock** [comment]
Fair enough, and thanks for your quick answer. ;)

By the way, have you guys ever considered adding Packaging images to the entries in the database?

**Comment by N3evin** [comment]
We currently have no plans for it. It should be done by individual application that is using the api.

**Comment by mr-rock** [comment]
I see. Thanks for the explanations about the philosophy and vision of the project.
