### ISSUE TITLE
Add Ena and Razewing Ratha from MHS2

### ISSUE THREAD

**Issue by lookye** [N3evin/AmiiboAPI#77]
Please add Ena and Razewing Ratha from Monster Hunter Stories 2: Wings of Ruin 

		"0x35060000040D0F02":
		{
			"name": "Ena",
			"release":
			{
				"au": "2021-07-09",
				"eu": "2021-07-09",
				"jp": "2021-07-09",
				"na": "2021-07-09"
			}
		},

and

		"0x35050000040C0F02":
		{
			"name": "Razewing Ratha",
			"release":
			{
				"au": "2021-07-09",
				"eu": "2021-07-09",
				"jp": "2021-07-09",
				"na": "2021-07-09"
			}
		},

Infos from the amiibos read with Tagmo.

**Comment by N3evin** [comment]
Updated, only issue is game_info as there's some issue with https://github.com/MrKev312/AmiiboGameListGenerator

**Comment by lookye** [comment]
Thanks for adding them.

Got Tsukino too and wanted to add this without another open "issue".

	"0x35070000040E0F02":
	{
		"name": "Tsukino",
		"release":
		{
			"au": "2021-07-09",
			"eu": "2021-07-09",
			"jp": "2021-07-09",
			"na": "2021-07-09"
		}
	},

**Comment by N3evin** [comment]
> Thanks for adding them.
> 
> Got Tsukino too and wanted to add this without another open "issue".
> 
> ```
> "0x35070000040E0F02":
> {
> 	"name": "Tsukino",
> 	"release":
> 	{
> 		"au": "2021-07-09",
> 		"eu": "2021-07-09",
> 		"jp": "2021-07-09",
> 		"na": "2021-07-09"
> 	}
> },
> ```

Thank you :) Added it in, feel free to open a new one if it's already closed. Worried I would forget about it.
