### ISSUE TITLE
Add the Yu-Gi-Oh amiibos

### ISSUE THREAD

**Issue by Ericzion1999** [N3evin/AmiiboAPI#78]
[
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Asana Mutsuba",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38460001",
			
			"name": "Asana Mutsuba",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "042A1902",
			"type": "Card"

 [
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Gakuto Sogetsu",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38420001",
			
			"name": "Gakuto Sogetsu",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04261902",
			"type": "Card"

 [
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Nail Saionji",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38450001",
			
			"name": "Nail Saionji",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04291902",
			"type": "Card"

[
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Roa Kirishima",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38440001",
			
			"name": "Roa Kirishima",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04281902",
			"type": "Card"

 [
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Romin Kirishima",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38430001",
			
			"name": "Romin Kirishima",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04271902",
			"type": "Card"

 [
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Tatsuhisa "Luke" Kamijo",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38410001",
			
			"name": "Tatsuhisa "Luke" Kamijo",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04251902",
			"type": "Card"

 
[
		{
			"amiiboSeries": "Yu-Gi-Oh!",
			"character": "Yuga Ohdo",
			"gameSeries": "Yi-Gi-Oh!",
			"head": "38400001",
			
			"name": "Yuga Ohdo",
			"release": {
				"au": null,
				"eu": null,
				"jp": "2021-08-12",
				"na": null
			},
			"tail": "04241902",
			"type": "Card"

**Comment by N3evin** [comment]
Required a clearer card image.

**Comment by N3evin** [comment]
Created a branch for it, will be added if anyone managed to get the images for the cards.
https://github.com/N3evin/AmiiboAPI/tree/feature/yu-gi-oh

**Comment by Ericzion1999** [comment]
I have a normal picture from Them , will they be OK?

**Comment by N3evin** [comment]
Yeah, if you have the images.

**Comment by Ericzion1999** [comment]
I have 4/7 Pictures 

https://drive.google.com/folderview?id=1IXfHgqGMXl_b2FUPsN75oV536rxKLz_E

**Comment by My1** [comment]
I can throw in nail later

**Comment by Ericzion1999** [comment]
I just discovered a bug, it's called Yuga Ohdo and not Yuga oudou, I'm sorry

**Comment by My1** [comment]
> I just discovered a bug, it's called Yuga Ohdo and not Yuga oudou, I'm sorry

are there even official Translations of the name? there are tons of ways to transcribe these names.

**Comment by Ericzion1999** [comment]
I have the names from yugipedia.com and Nintendowire

**Comment by N3evin** [comment]
yeah, i think you are right about the naming. I will do it this weekend. As I am currently not home with my laptop.

**Comment by Ericzion1999** [comment]
I Hope this Images are good 😅

https://drive.google.com/folderview?id=1Kha_EsID95dYc5MpvCdoermkkEcvSWyl

**Comment by N3evin** [comment]
Completed :) Thanks for the images. Had been merged to the server. This issue will be closed. So if there's any other issue. Feel free to open a new one.

https://github.com/N3evin/AmiiboAPI/commit/22106444e3a6e18ec8363a6a1ee094a12e4500a7
