### ISSUE TITLE
Metroid dread 

### ISSUE THREAD

**Issue by Ericzion1999** [N3evin/AmiiboAPI#81]

**Comment by Ericzion1999** [comment]
![Screenshot_2021-10-09-17-33-46-226_com.hiddenramblings.tagmo.jpg](https://user-images.githubusercontent.com/82835573/136665003-751d3ed5-3b24-4e0b-aa20-297f4ddae1f2.jpg)

**Comment by Ericzion1999** [comment]
![Screenshot_2021-10-09-17-37-54-418_com.android.chrome.jpg](https://user-images.githubusercontent.com/82835573/136665034-9eb0d74e-aa3b-4a32-8c0c-4896adef1b22.jpg)


Your Website dont have the Infos for Metroid dread amiibo's , or you must It First Upload to IT? 🤔

**Comment by N3evin** [comment]
> ![Screenshot_2021-10-09-17-37-54-418_com.android.chrome.jpg](https://user-images.githubusercontent.com/82835573/136665034-9eb0d74e-aa3b-4a32-8c0c-4896adef1b22.jpg)
> 
> Your Website dont have the Infos for Metroid dread amiibo's , or you must It First Upload to IT? 🤔

I don't do a codepipeline for deployment. To make sure the stuff is actually working properly :)

Bug:
- game_info is not compiling.

https://github.com/N3evin/AmiiboAPI/blob/master/database/games_info.json

I had made an issue report, and see if the developer could solve it.
https://github.com/MrKev312/AmiiboGameListGenerator/issues/4

**Comment by N3evin** [comment]
You know what, I will just go ahead and deploy and just leave the 2 game_info as empty for now till the dev had fix it.

**Comment by N3evin** [comment]
Go ahead, give it a try :) It's up on amiiboapi. Thank you!

**Comment by N3evin** [comment]
Fully updated! Can be close

> > You know what, I will just go ahead and deploy and just leave the 2 game_info as empty for now till the dev had fix it.
> 
> What i have to do with the amiibogamelist ,so that the games_info is updated?
You have to look at the repo own by the other developer.
