### ISSUE TITLE
I See the Pictures but Not the name

### ISSUE THREAD

**Issue by Ericzion1999** [N3evin/AmiiboAPI#84]
![Screenshot_2021-11-05-17-10-48-566_com.hiddenramblings.tagmo.jpg](https://user-images.githubusercontent.com/82835573/140546836-8d672f23-52c1-4f70-bdff-94e89ac91bec.jpg)

**Comment by N3evin** [comment]
Give it a try again?

**Comment by Ericzion1999** [comment]
Yes , but still the Same

**Comment by Ericzion1999** [comment]
i have Install tagmo newest Version , And now IT Work ![Screenshot_2021-11-05-19-31-36-513_com.hiddenramblings.tagmo.jpg](https://user-images.githubusercontent.com/82835573/140561251-2623f790-5327-4c6d-98e9-0d1e045e9dc7.jpg)

**Comment by N3evin** [comment]
So it was not the API, just that you had tagmo issue? Then, please do push it to tagmo issue for the future.
