### ISSUE TITLE
Missing Sanrio Animal Crossing Amiibos

### ISSUE THREAD

**Issue by TerraFlareKSFL** [N3evin/AmiiboAPI#86]
@ title.
Just noticed 2 Sanrio character cards are missing (Suppose to be 6 in total)
--#1 Rilla
--#3 Etoile
API has the other 4 listed and they appear in Emuiibo, but the 2 listed above are missing from the API.

**Comment by cheatfreak47** [comment]
Both of these *are* in the API already.
Étoile has an accent over the E as part of her actual name (pictured on the card as well).
Emuiibo might be to blame here.

```json
		"0x04d30101031b0502":
		{
			"name": "\u00c9toile",
			"release":
			{
				"au": null,
				"eu": "2016-11-25",
				"jp": "2016-11-03",
				"na": null
			}
		},
		"0x0374010103190502":
		{
			"name": "Rilla",
			"release":
			{
				"au": null,
				"eu": "2016-11-25",
				"jp": "2016-11-03",
				"na": null
			}
		},
```
