### ISSUE TITLE
German names 

### ISSUE THREAD

**Issue by Ericzion1999** [N3evin/AmiiboAPI#89]
Hy , is it possible to make a Database With the german amiibo names? Or to edit the amiibo.json ?

**Comment by N3evin** [comment]
Hi! Currently we have no plans on other localisation.

**Comment by Ericzion1999** [comment]
Thats okay, how can i edit the json File , that i have the German names ?

**Comment by N3evin** [comment]
Yes, but you might need to modify the code to handle it too. Unless you just modified the json file for your own use :)

**Comment by Ericzion1999** [comment]
how do I do that?

**Comment by Ericzion1999** [comment]
I have edit the amiibo.json , when I only changed a few names everything worked but when I changed all names and imported it came this message appeared:![Screenshot_2021-12-07-08-18-40-839_com.hiddenramblings.tagmo.jpg](https://user-images.githubusercontent.com/82835573/144984431-84e3e2e6-bf41-45a3-87bd-7863a0dd45af.jpg)
