### ISSUE TITLE
Certain Splatoon amiibo show up in-game as other ones

### ISSUE THREAD

**Issue by Spar955** [N3evin/AmiiboAPI#90]
Hi, I brought this to the attention of the amiigo dev, and was told to make an issue here, as this is likely a simple mislabeling. Using the Splatoon Inkling Girl - Neon Pink and Inkling Boy - Neon Green amiibos in Splatoon 2 via emuiibo on Switch cause them to show up as the Inkling Girl and Inkling Boy amiibos in-game (from Splatoon 1). I appreciate all the work that goes into this and hopefully this can be remedied!

**Comment by N3evin** [comment]
Do you happen to have the id of the amiibo? Or the bin it's being used?

From the db, it's the correct amiibo id.

**Comment by Spar955** [comment]
Thanks for the response! Do you know how I could go about converting bins to jsons?
