### ISSUE TITLE
Read Amiibo API via cURL or wget fails

### ISSUE THREAD

**Issue by JoshuaBehrens** [N3evin/AmiiboAPI#94]
`curl https://amiiboapi.com/api/amiibo/` and `wget https://amiiboapi.com/api/amiibo/` both fail to fetch the full list. They fail close to 2^16 bytes.

**Comment by N3evin** [comment]
Seems like due to the logs, it actually fills up the disk space. Will be looking into it.

**Comment by N3evin** [comment]
Is up, you can try it again :)

**Comment by JoshuaBehrens** [comment]
Hype is real. Works again :) Were you able to find a permanent solution?

**Comment by N3evin** [comment]
> Hype is real. Works again :) Were you able to find a permanent solution?

Not at this moment, unless I upgrade the storage space or restart the server regularly.

**Comment by JoshuaBehrens** [comment]
Snap. Then I will nudge you again when I notice :) thanks for the quick reaction
