### ISSUE TITLE
Add Card Series Number to Animal Crossing Amiibo Cards

### ISSUE THREAD

**Issue by KevinCCucumber** [N3evin/AmiiboAPI#99]
It would be very convenient to have this additional Data of wich Card series a card is part of. There are no other clues present on how to bundle the data.

**Comment by cesardka** [comment]
@N3evin is this possible? I am more than willing to help if needed to get that done! :)

**Comment by N3evin** [comment]
> @N3evin is this possible? I am more than willing to help if needed to get that done! :)

Hi, I do not plan to do that at all, but if you have a solution and would like to add it, feel free to fork out the repository :)
